title = "Thoughts, Ramblings and Writings by Tau"
base_url = "https://space.tau.garden"
compile_sass = true
minify_html = true

[extra]
feeds = ['_index.md']

[extra.meta]
me = 'https://hachyderm.io/@tautropfli'
